/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 12 18:16:51 GMT 2016
 */

package atm.physical;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import atm.physical.Log;
import banking.Message;
import banking.Money;
import banking.Status;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Log_ESTest extends Log_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Log log0 = new Log();
      // Undeclared exception!
      try { 
        log0.logSend((Message) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.Log", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Log log0 = new Log();
      // Undeclared exception!
      try { 
        log0.logCashDispensed((Money) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.Log", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Log log0 = new Log();
      // Undeclared exception!
      try { 
        log0.logResponse((Status) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.Log", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Log log0 = new Log();
      // Undeclared exception!
      try { 
        log0.logEnvelopeAccepted();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("atm.physical.Log", e);
      }
  }
}
